### ISSUE TITLE
Move to https://github.com/libp2p/js-libp2p/tree/master/examples?

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p-examples#12]

**Comment by vasco-santos** [comment]
I have mixed feelings here.

I was thinking about asking for opinions to do the opposite 😅 Personally, I would prefer to have all the examples here and `js-libp2p` referencing this repo.

**Comment by vasco-santos** [comment]
@daviddias have a look on my proposal on https://github.com/libp2p/js-libp2p/issues/512#issuecomment-564929701

**Comment by daviddias** [comment]
Reviewed! :)

**Comment by jacobheun** [comment]
Closing in favor if the proposal from above
