### ISSUE TITLE
enable discussions

### ISSUE THREAD

**Issue by st3b1t** [libp2p/js-libp2p-examples#132]
probably enable discussion in this repo might be helpful, it's about example of use, there are many questions devs would like to ask approaching this library

**Comment by achingbrain** [comment]
My concern with this is that discussions would be missed as it's another channel that needs to be regularly checked - the [main js-libp2p discussion board](https://github.com/libp2p/js-libp2p/discussions) is linked to from all example READMEs, hopefully we can concentrate discussions there - it's got more eyeballs on it so hopefully people will be able to get help faster.

Thanks for the suggestion - closing this for now but we can revisit if it doesn't work out.
