### ISSUE TITLE
ReferenceError: CustomEvent is not defined

### ISSUE THREAD

**Issue by zhenguang** [libp2p/js-libp2p-examples#179]
All the examples shows this

file:///Users/xxx/Documents/projects/xxx/js-libp2p-examples/node_modules/@libp2p/interface/dist/src/event-target.js:53
        return this.dispatchEvent(new CustomEvent(type, detail));
                                      ^

ReferenceError: CustomEvent is not defined
    at EventTarget.safeDispatchEvent (file:///Users/xxxx/Documents/projects/xxx/js-libp2p-examples/node_modules/@libp2p/interface/dist/src/event-target.js:53:39)
    
    Is there anything wrong with the version?

**Comment by SgtPooki** [comment]
@zhenguang what version of NodeJS are you using? [js-libp2p@2.0 removed the `CustomEvent` polyfill](https://github.com/libp2p/js-libp2p/blob/main/doc/migrations/v1.0.0-v2.0.0.md#the-customevent-polyfill-has-been-removed-from-libp2pinterface) but it should be available in the LTS version of NodeJS

<img width="398" alt="image" src="https://github.com/user-attachments/assets/d4261acd-d1bc-489f-a345-8473fa02679e">


### References

* https://github.com/libp2p/js-libp2p/blob/main/doc/migrations/v1.0.0-v2.0.0.md#the-customevent-polyfill-has-been-removed-from-libp2pinterface
* https://nodejs.org/api/events.html#class-customevent

**Comment by zhenguang** [comment]
Thanks, it's working after using 22.1.0
