### ISSUE TITLE
Pubsub error when running the index.js 

### ISSUE THREAD

**Issue by sirhc-sch** [libp2p/js-libp2p-examples#3]
I get the following error in the console when running the index.js of the 08-End example. 

libp2pWS/chat/nodejs/node_modules/libp2p/src/config.js:95
Expected a value of type `undefined` for `config.EXPERIMENTAL` but received `{"pubsub":true}`.

Does anyone have the same ?

**Comment by jacobheun** [comment]
Can you check the version of libp2p you have installed via `npm ls libp2p`? 

0.25.4 should be installed if you ran `npm clean-install`. It looks like a newer version of libp2p was installed, which would require an update to the config for pubsub.

**Comment by DatawarehouseMonkey** [comment]
if I run npm clean-install I get version 0.26.2

**Comment by jacobheun** [comment]
Has your package lock changed from when the project was originally cloned? clean install with a package-lock should prevent the packages from being updated.

**Comment by achingbrain** [comment]
Closing due to staleness.
