### ISSUE TITLE
high severity vulnerabilities

### ISSUE THREAD

**Issue by Giancarlo1974** [libp2p/js-libp2p-examples#36]
I tried the chat example
I have seen that the examples use a vulnerable version

`npm clean-install`

**added 374 packages, and audited 375 packages in 35s
8 high severity vulnerabilities**

After running the command
`npm audit fix --force`

08-End example gives me a series of errors

Can you update the example with the version of the library without vulnerabilities?

which version of node is recommended?

**Comment by vasco-santos** [comment]
Thanks for reaching out @Giancarlo1974 .Would you like to update the problematic deps and submit a PR? This examples repo is not actively maintained at the moment
