### ISSUE TITLE
Tutorials needs more clarity, otherwise not very useful for beginners

### ISSUE THREAD

**Issue by tesla809** [libp2p/js-libp2p-examples#4]
Not a very clear tutorial. Feels more like copy pasta than any substantive explanation of whats is going on.

Would there be a way to clear it up? Or to create one simple example application that highlights the main parts of libp2p?

I'm trying to find resources and so far nothing is very helpful.

**Comment by jacobheun** [comment]
Some of the TODOs in the code need to be cleaned up, I also noticed that the original slide deck this is built around isn't linked anywhere. This was created for IPFS Camp and the presentation can be viewed here, https://docs.google.com/presentation/d/1a_BjIM4ORQchnMNjOMO-wCDW2VS5nXeKXIbWSEqf9jY/edit. It includes speak notes, which includes most of the dialogue from the workshop. Does that provide enough clarity, or do you think there are still some gaps?

**Comment by achingbrain** [comment]
Closing due to staleness.
