### ISSUE TITLE
Missing examples linked in README

### ISSUE THREAD

**Issue by jmatsushita** [libp2p/js-libp2p-examples#72]
Hi there,

Wondering where did the `libp2p-in-the-browser` examples went? The 3 links in [this section of the README](https://github.com/libp2p/js-libp2p-examples#libp2p-in-the-browser) are pointing nowhere. I'm most interested in these examples, but when trying to understand what happened, I thought I'd dig a bit deeper and found some other things missing.

If I understand correctly, right before https://github.com/libp2p/js-libp2p/pull/2171 was merged, there were all in here https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples with this list:
 - [auto-relay](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/auto-relay)
 - [chat](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/chat)
 - [connection-encryption](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/connection-encryption)
 - [delegated-routing](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/delegated-routing)
 - [discovery-mechanisms](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/discovery-mechanisms)
 - [echo](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/echo)
 - [libp2p-in-the-browser](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/libp2p-in-the-browser)
   - [webrtc](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/libp2p-in-the-browser/webrtc)
   - [websockets](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/libp2p-in-the-browser/websockets)
   - [webtransport/fetch-file-from-kubo](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/libp2p-in-the-browser/webtransport/fetch-file-from-kubo)
 - [peer-and-content-routing](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/peer-and-content-routing)
 - [pnet](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/pnet)
 - [protocol-and-stream-muxing](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/protocol-and-stream-muxing)
 - [pubsub](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/pubsub)
 - [transports](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples/transports)

But it seems only a few of them made it as a separate repo? I can see:
 - https://github.com/libp2p/js-libp2p-examples (which seems to contain a copy of the 4 repos below as explained in the [PR](https://github.com/libp2p/js-libp2p/pull/2171#issue-1961578945))
 - https://github.com/libp2p/js-libp2p-example-browser-pubsub
 - https://github.com/libp2p/js-libp2p-example-connection-encryption
 - https://github.com/libp2p/js-libp2p-example-chat 
 - https://github.com/libp2p/js-libp2p-example-circuit-relay
 
I'm most interested in the `libp2p-in-the-browser/webrtc` example, but hopefully it's helpful to have a list of the other ones 😄 

CC @achingbrain

**Comment by achingbrain** [comment]
Ah, yes - they're coming back, I've not finished porting them over to this newer format yet.

They are all still in the [libp2p repo commit history](https://github.com/libp2p/js-libp2p/tree/c6db2104dbe4257e14e66cda75bd8daf6a27f3c5/examples) - hopefully this is enough for you to get on with things.

**Comment by achingbrain** [comment]
It's taken a bit of time but the examples have been migrated to the new version of libp2p and updated here.  Some with duplicated content have been omitted, and there should be some new ones when node.js gets QUIC support.

Thanks for opening this issue!
